### ISSUE TITLE
Duckdns issue

### ISSUE THREAD

**Issue by daeiron** [eatonc/actual-gcp#11]
Hi, 

I just tried this and everything is running fine except I cant access my duckdns site.

Caddy throws this error:

`{"level":"error","ts":1741378187.2406147,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"actualbudgettvg.duckdns.org","issuer":"acme-v02.api.letsencrypt.org-directory","error":"HTTP 400 urn:ietf:params:acme:error:connection - 35.211.143.150: Fetching http://actualbudgettvg.duckdns.org/.well-known/acme-challenge/sDBVtjRj_TieSbtJFMzDZJpsS1dDf6WXmeSdYfqtqK8: Timeout during connect (likely firewall problem)"}
{"level":"error","ts":1741378187.2407901,"logger":"tls.obtain","msg":"will retry","error":"[actualbudgettvg.duckdns.org] Obtain: [actualbudgettvg.duckdns.org] solving challenge: actualbudgettvg.duckdns.org: [actualbudgettvg.duckdns.org] authorization failed: HTTP 400 urn:ietf:params:acme:error:connection - 35.211.143.150: Fetching http://actualbudgettvg.duckdns.org/.well-known/acme-challenge/sDBVtjRj_TieSbtJFMzDZJpsS1dDf6WXmeSdYfqtqK8: Timeout during connect (likely firewall problem) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":5,"retrying_in":600,"elapsed":729.688243178,"max_duration":2592000}`

The IP is set correctly in duckdns and so are the firewall rules in google cloud.

Any ideas?

**Comment by DevMattM** [comment]
Hey, I just went through this set up last week and I ran into similar issues because the drive was not mounting successfully. I think this was causing issues storing certs, synced files and everything else. Check if the drive is mounted lsblk. It might be easier to just follow the last comment from @eatonc  here: https://github.com/eatonc/actual-gcp/issues/10

**Comment by eatonc** [comment]
@daeiron / @DevMattM - Thanks for opening the issue. Sorry it's taken me a bit to get around to looking at this. I think this problem was caused by not having a firewall rule in place that opens up port 80 to the compute engine instance. Per [Caddy's documentation](https://caddyserver.com/docs/automatic-https#http-challenge), port 80 must be externally accessible in order for the TLS certificate process to work.

Notably, Caddy automatically redirects port 80 to HTTPS, so there is not a security concern with allowing this traffic. I've pushed changes to add the HTTP firewall rule and add the appropriate tag to the compute engine instance to enable port 80. This should resolve the timeout errors you're seeing during Caddy startup and certificate generation.

**Comment by mtShaikh** [comment]
@eatonc I'm still facing the same issue. I cloned the repository today. My drive seems to mounted. 😕 
would like some insights on how to fix it

![Image](https://github.com/user-attachments/assets/b740427f-4346-4e93-88b0-dc00fb618f3c)

**Comment by eatonc** [comment]
Hi @mtShaikh. When you say you're facing the same issue, do you mean that you see timeouts in the Caddy logs?

**Comment by mtShaikh** [comment]
Yes I'm seeing timeouts as well. 

```
{"level":"info","ts":1743881508.6247494,"msg":"trying to solve challenge","identifier":"budgets.duckdns.org","challenge_type":"http-01","ca":"https://acme-v02.api.letsencrypt.org/directory"}
{"level":"error","ts":1743881519.2398405,"msg":"challenge failed","identifier":"budgets.duckdns.org","challenge_type":"http-01","problem":{"type":"urn:ietf:params:acme:error:connection","title":"","detail":"35.208.214.72: Fetching http://budgets.duckdns.org/.well-known/acme-challenge/QmASV1vbg6z5G_Ia2zyVInrO24_ZMdap8NcGslk7boI: Timeout during connect (likely firewall problem)","instance":"","subproblems":null},"stacktrace":"github.com/mholt/acmez/v3.(*Client).pollAuthorization\n\tgithub.com/mholt/acmez/v3@v3.0.0/client.go:557\ngithub.com/mholt/acmez/v3.(*Client).solveChallenges\n\tgithub.com/mholt/acmez/v3@v3.0.0/client.go:378\ngithub.com/mholt/acmez/v3.(*Client).ObtainCertificate\n\tgithub.com/mholt/acmez/v3@v3.0.0/client.go:136\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).doIssue\n\tgithub.com/caddyserver/certmagic@v0.21.6/acmeissuer.go:477\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).Issue\n\tgithub.com/caddyserver/certmagic@v0.21.6/acmeissuer.go:399\ngithub.com/caddyserver/caddy/v2/modules/caddytls.(*ACMEIssuer).Issue\n\tgithub.com/caddyserver/caddy/v2@v2.9.1/modules/caddytls/acmeissuer.go:249\ngithub.com/caddyserver/certmagic.(*Config).obtainCert.func2\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:626\ngithub.com/caddyserver/certmagic.doWithRetry\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:104\ngithub.com/caddyserver/certmagic.(*Config).obtainCert\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:700\ngithub.com/caddyserver/certmagic.(*Config).ObtainCertAsync\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:505\ngithub.com/caddyserver/certmagic.(*Config).manageOne.func1\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:415\ngithub.com/caddyserver/certmagic.(*jobManager).worker\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:73"}
{"level":"error","ts":1743881519.2400208,"msg":"validating authorization","identifier":"budgets.duckdns.org","problem":{"type":"urn:ietf:params:acme:error:connection","title":"","detail":"35.208.214.72: Fetching http://budgets.duckdns.org/.well-known/acme-challenge/QmASV1vbg6z5G_Ia2zyVInrO24_ZMdap8NcGslk7boI: Timeout during connect (likely firewall problem)","instance":"","subproblems":null},"order":"https://acme-v02.api.letsencrypt.org/acme/order/2323943617/371093883687","attempt":2,"max_attempts":3,"stacktrace":"github.com/mholt/acmez/v3.(*Client).ObtainCertificate\n\tgithub.com/mholt/acmez/v3@v3.0.0/client.go:152\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).doIssue\n\tgithub.com/caddyserver/certmagic@v0.21.6/acmeissuer.go:477\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).Issue\n\tgithub.com/caddyserver/certmagic@v0.21.6/acmeissuer.go:399\ngithub.com/caddyserver/caddy/v2/modules/caddytls.(*ACMEIssuer).Issue\n\tgithub.com/caddyserver/caddy/v2@v2.9.1/modules/caddytls/acmeissuer.go:249\ngithub.com/caddyserver/certmagic.(*Config).obtainCert.func2\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:626\ngithub.com/caddyserver/certmagic.doWithRetry\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:104\ngithub.com/caddyserver/certmagic.(*Config).obtainCert\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:700\ngithub.com/caddyserver/certmagic.(*Config).ObtainCertAsync\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:505\ngithub.com/caddyserver/certmagic.(*Config).manageOne.func1\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:415\ngithub.com/caddyserver/certmagic.(*jobManager).worker\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:73"}
{"level":"error","ts":1743881519.2401388,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"budgets.duckdns.org","issuer":"acme-v02.api.letsencrypt.org-directory","error":"HTTP 400 urn:ietf:params:acme:error:connection - 104.208.214.72: Fetching http://budgets.duckdns.org/.well-known/acme-challenge/QmASV1vbg6z5G_Ia2zyVInrO24_ZMdap8NcGslk7boI: Timeout during connect (likely firewall problem)"}
{"level":"info","ts":1743881519.240189,"logger":"tls.obtain","msg":"releasing lock","identifier":"budgets.duckdns.org"}
{"level":"error","ts":1743881519.2402785,"logger":"tls","msg":"job failed","error":"budgets.duckdns.org: obtaining certificate: [budgets.duckdns.org] Obtain: [budgets.duckdns.org] solving challenge: budgets.duckdns.org: [budgets.duckdns.org] authorization failed: HTTP 400 urn:ietf:params:acme:error:connection - 104.208.214.72: Fetching http://budgets.duckdns.org/.well-known/acme-challenge/QmASV1vbg6z5G_Ia2zyVInrO24_ZMdap8NcGslk7boI: Timeout during connect (likely firewall problem) (ca=https://acme-v02.api.letsencrypt.org/directory)"}
```

**Comment by mtShaikh** [comment]
yes i'm seeing timeouts as well

```
{"level":"info","ts":1743881508.6247494,"msg":"trying to solve challenge","identifier":"budgets.duckdns.org","challenge_type":"http-01","ca":"https://acme-v02.api.letsencrypt.org/directory"}
{"level":"error","ts":1743881519.2398405,"msg":"challenge failed","identifier":"budgets.duckdns.org","challenge_type":"http-01","problem":{"type":"urn:ietf:params:acme:error:connection","title":"","detail":"104.208.214.72: Fetching http://budgets.duckdns.org/.well-known/acme-challenge/QmASV1vbg6z5G_Ia2zyVInrO24_ZMdap8NcGslk7boI: Timeout during connect (likely firewall problem)","instance":"","subproblems":null},"stacktrace":"github.com/mholt/acmez/v3.(*Client).pollAuthorization\n\tgithub.com/mholt/acmez/v3@v3.0.0/client.go:557\ngithub.com/mholt/acmez/v3.(*Client).solveChallenges\n\tgithub.com/mholt/acmez/v3@v3.0.0/client.go:378\ngithub.com/mholt/acmez/v3.(*Client).ObtainCertificate\n\tgithub.com/mholt/acmez/v3@v3.0.0/client.go:136\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).doIssue\n\tgithub.com/caddyserver/certmagic@v0.21.6/acmeissuer.go:477\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).Issue\n\tgithub.com/caddyserver/certmagic@v0.21.6/acmeissuer.go:399\ngithub.com/caddyserver/caddy/v2/modules/caddytls.(*ACMEIssuer).Issue\n\tgithub.com/caddyserver/caddy/v2@v2.9.1/modules/caddytls/acmeissuer.go:249\ngithub.com/caddyserver/certmagic.(*Config).obtainCert.func2\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:626\ngithub.com/caddyserver/certmagic.doWithRetry\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:104\ngithub.com/caddyserver/certmagic.(*Config).obtainCert\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:700\ngithub.com/caddyserver/certmagic.(*Config).ObtainCertAsync\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:505\ngithub.com/caddyserver/certmagic.(*Config).manageOne.func1\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:415\ngithub.com/caddyserver/certmagic.(*jobManager).worker\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:73"}
{"level":"error","ts":1743881519.2400208,"msg":"validating authorization","identifier":"budgets.duckdns.org","problem":{"type":"urn:ietf:params:acme:error:connection","title":"","detail":"104.208.214.72: Fetching http://budgets.duckdns.org/.well-known/acme-challenge/QmASV1vbg6z5G_Ia2zyVInrO24_ZMdap8NcGslk7boI: Timeout during connect (likely firewall problem)","instance":"","subproblems":null},"order":"https://acme-v02.api.letsencrypt.org/acme/order/2323943617/371093883687","attempt":2,"max_attempts":3,"stacktrace":"github.com/mholt/acmez/v3.(*Client).ObtainCertificate\n\tgithub.com/mholt/acmez/v3@v3.0.0/client.go:152\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).doIssue\n\tgithub.com/caddyserver/certmagic@v0.21.6/acmeissuer.go:477\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).Issue\n\tgithub.com/caddyserver/certmagic@v0.21.6/acmeissuer.go:399\ngithub.com/caddyserver/caddy/v2/modules/caddytls.(*ACMEIssuer).Issue\n\tgithub.com/caddyserver/caddy/v2@v2.9.1/modules/caddytls/acmeissuer.go:249\ngithub.com/caddyserver/certmagic.(*Config).obtainCert.func2\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:626\ngithub.com/caddyserver/certmagic.doWithRetry\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:104\ngithub.com/caddyserver/certmagic.(*Config).obtainCert\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:700\ngithub.com/caddyserver/certmagic.(*Config).ObtainCertAsync\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:505\ngithub.com/caddyserver/certmagic.(*Config).manageOne.func1\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:415\ngithub.com/caddyserver/certmagic.(*jobManager).worker\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:73"}
{"level":"error","ts":1743881519.2401388,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"budgets.duckdns.org","issuer":"acme-v02.api.letsencrypt.org-directory","error":"HTTP 400 urn:ietf:params:acme:error:connection - 104.208.214.72: Fetching http://budgets.duckdns.org/.well-known/acme-challenge/QmASV1vbg6z5G_Ia2zyVInrO24_ZMdap8NcGslk7boI: Timeout during connect (likely firewall problem)"}
{"level":"info","ts":1743881519.240189,"logger":"tls.obtain","msg":"releasing lock","identifier":"budgets.duckdns.org"}
{"level":"error","ts":1743881519.2402785,"logger":"tls","msg":"job failed","error":"budgets.duckdns.org: obtaining certificate: [budgets.duckdns.org] Obtain: [budgets.duckdns.org] solving challenge: budgets.duckdns.org: [budgets.duckdns.org] authorization failed: HTTP 400 urn:ietf:params:acme:error:connection - 104.208.214.72: Fetching http://budgets.duckdns.org/.well-known/acme-challenge/QmASV1vbg6z5G_Ia2zyVInrO24_ZMdap8NcGslk7boI: Timeout during connect (likely firewall problem) (ca=https://acme-v02.api.letsencrypt.org/directory)"}
```

**Comment by eatonc** [comment]
You mentioned you cloned it down today, right? So your VM has the http-server tag applied to it, as defined on line 4 of `terraform.tfvars`?

```
container_host_network_tags = ["allow-ssh-proxy", "https-server", "http-server"]
```

These would also be reflected under the Network Tags section when inspecting the Compute Engine instance in the Google Cloud console, or under the Tags section if you run the CLI command `cloud compute instances describe instance_name`.

Please also confirm that the "allow-http" firewall rule was created by navigating to VPC Network > Firewall in the Google Cloud console, or by using the CLI command `gcloud compute firewall-rules list`.

**Comment by mtShaikh** [comment]
Thanks for the help @eatonc 

Yes I can see the tags both on the console and in the cli command 
the "allow-http" firewall rule is also there. 

![Image](https://github.com/user-attachments/assets/af109d28-d59d-4188-beb6-06e8de0b53fd)

![Image](https://github.com/user-attachments/assets/7259cc9f-845e-44f7-996f-4b3732154fcc)

**Comment by eatonc** [comment]
@mtShaikh - Thanks for confirming that the rules are in-place. The next steps I would ask you to confirm is that your DuckDNS domain name is set correctly (the values you're passing in for the `actual_fqdn` and `duckdns_subdomains` variables), and that your Compute Engine instance's public IP address is reflecting in your DuckDNS dashboard. This should be happening automatically by the duckdns container that starts up, but manual confirmation would probably be good.

**Comment by mtShaikh** [comment]
Yes @eatonc the `actual_fqdn` and `duckdns_subdomains` are reflecting the duckdns domain and the public ip is being reflected in the duckdns dashboard.
